project:
  type: website
  output-dir: docs

website:
  title: "NCRMP Fish R Package"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Installation"
        href: installation.qmd
      - text: "Downloading Data"
        href: downloading.qmd
      - text: "Quick Start"
        href: quick-start.qmd
      - text: "Function Reference"
        menu:
          - text: "Abundance"
            href: functions/estimate-abundance.qmd
          - text: "Biomass"
            href: functions/estimate-biomass.qmd
          - text: "Total Biomass"
            href: functions/estimate-totalbiomass.qmd
          - text: "Density"
            href: functions/estimate-density.qmd
          - text: "Occurrence"
            href: functions/estimate-occurrence.qmd
          - text: "Length Frequency"
            href: functions/estimate-lf.qmd
          - text: "Length"
            href: functions/estimate-lbar.qmd
      - text: "Visualization"
        href: visualization.qmd
      - text: "Troubleshooting"
        href: troubleshooting.qmd
      - text: "Appendix"
        href: appendix.qmd
  page-footer:
    left: "Â© 2025 Jeremiah Blondeau|NOAA Fisheries"
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme: cosmo
    toc: true